"""D4 (fair baseline protocol) learning-rate selection and follow-up job generation.

Implements the selection half of R2_EXPERIMENT_PLAN.md D4 + section 4 ("Adopted / D4").
Stage-1 jobs themselves are generated by `make_r2_jobs.py --stage d4_tune`; this script
never re-implements the job-line format -- it imports `make_r2_jobs` and calls
`m3_job` / `lr_tag`, so the emitted lines and the `# out=` annotations stay identical
to package A's by construction.

Protocol implemented here
-------------------------
score(run)        mean of `records[*].metric` over the last 20 % of the run, i.e. every
                  logged record with  step >= 0.8 * args.steps  (`--frac` to change).
                  args.steps is read per run, so the 6 000-step screen and the
                  20 000-step stage-2 runs each use their own window.
score(config)     unweighted mean of the two per-seed scores -- the seed is the unit of
                  aggregation, never the pooled record set.
direction         run_m3.py logs `metric` = accuracy for the cross-entropy tasks
                  (copy, anbn) and the MSE value for every other D4 task, so the former
                  are maximised and the latter minimised (see `verify-direction`).
eligibility       a config competes only when every tuning seed produced a usable score;
                  a non-finite window mean (divergence) ranks last.
ties              broken towards the smaller learning rate, then the smaller TBPTT
                  window; every tie is reported.
boundary          if the winner sits at the edge of the explored LR set (and the whole
                  base grid is complete for that pair) the grid is extended one rung
                  outwards on the 1-3 ladder, at most twice (`--max-extend`).
stage 2           the top-2 configs per (task, algo) are re-run at 20 000 steps with the
                  same tuning seeds; the winner there is the final LR.
evaluation        final LR x seeds 0-9 x 20 000 steps, shadow on.

Sub-commands
------------
  select --stage 1        read <indir> (default results/r2/d4_tune)   -> D4_SELECT_stage1.{md,json}
  select --stage 2        read <indir> (default results/r2/d4_stage2) -> D4_SELECT_stage2.{md,json}
  emit --what boundary    -> jobs/d4_boundary.txt  (stage-1 supplements: LR extension + TBPTT window fill)
  emit --what stage2      -> jobs/d4_stage2.txt
  emit --what eval        -> jobs/d4_eval.txt
  status                  completion / missing counts per stage
  verify-direction        cross-check the metric-direction table against skrtrl/tasks.py

Relative paths are resolved against this script's directory (code/), exactly like
run_r2_queue.ps1 does, so the same string works from anywhere.

This script never launches anything.
"""
from __future__ import annotations

import argparse
import ast
import json
import math
import os
import re
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import make_r2_jobs as mj          # noqa: E402  read-only: single source of truth for job lines

_REQUIRED = ["TASKS_D4", "ALGOS_D4", "LRS_D4", "SEEDS_TUNE", "STEPS_TUNE", "lr_tag", "m3_job"]
_absent = [a for a in _REQUIRED if not hasattr(mj, a)]
if _absent:
    raise SystemExit("make_r2_jobs.py no longer exposes %s -- the D4 job-line format "
                     "changed; fix make_r2_d4_select.py before emitting anything." % _absent)

# ---------------------------------------------------------------- protocol constants
TASKS = list(mj.TASKS_D4)
ALGOS = list(mj.ALGOS_D4)
BASE_LRS = list(mj.LRS_D4)
SEEDS_TUNE = list(mj.SEEDS_TUNE)
STEPS_TUNE = int(mj.STEPS_TUNE)
STEPS_STAGE2 = 20000
STEPS_EVAL = 20000
SEEDS_EVAL = list(range(10))
WINDOW_FRAC = 0.8
MAX_EXTEND = 2
TOP_K_STAGE2 = 2

TBPTT_ALGOS = {a for a in ALGOS if a.startswith("tbptt")}
# plan section 4, D4: "TBPTT window in {25, 50} tuned with the same budget"
TBPTT_WINDOWS = list(getattr(mj, "TBPTT_WINDOWS_D4", [25, 50]))
TBPTT_DEFAULT_WINDOW = 25          # run_m3.py --tbptt_k default; re-checked in _detect_window_flag

# metric direction: run_m3.py / skrtrl.train.Learner.loss_fn returns accuracy for
# loss_type "ce" and the MSE value for loss_type "mse".
HIGHER_IS_BETTER = {"copy", "anbn"}

DEFAULT_DIRS = {1: "results/r2/d4_tune", 2: "results/r2/d4_stage2"}
EVAL_DIR = "results/r2/d4_eval"
REPORT_DIR = "results/r2"
JOBS_DIR = "jobs"
JOB_FILES = {"boundary": "d4_boundary.txt", "stage2": "d4_stage2.txt", "eval": "d4_eval.txt"}


def rel(path):
    """Resolve a possibly relative path against code/ (the queue's working directory)."""
    return path if os.path.isabs(path) else os.path.normpath(os.path.join(HERE, path))


# ---------------------------------------------------------------- LR ladder (1-3 decades)
def _build_ladder():
    return sorted(m * (10.0 ** e) for e in range(-7, 0) for m in (1.0, 3.0))


LADDER = _build_ladder()
LADDER_TAGS = [mj.lr_tag(x) for x in LADDER]
_TAG2IDX = {t: i for i, t in enumerate(LADDER_TAGS)}
if len(_TAG2IDX) != len(LADDER_TAGS):
    raise SystemExit("lr_tag() is not injective on the 1-3 ladder")

_base_idx = [_TAG2IDX.get(mj.lr_tag(l)) for l in BASE_LRS]
if any(i is None for i in _base_idx):
    raise SystemExit("base LR grid %s is not on the 1-3 ladder; extend _build_ladder()" % BASE_LRS)
I_LO, I_HI = min(_base_idx), max(_base_idx)
if sorted(_base_idx) != list(range(I_LO, I_HI + 1)):
    print("[warn] base LR grid is not contiguous on the 1-3 ladder; boundary levels are "
          "measured from its extremes only", file=sys.stderr)


def lr_of_tag(tag):
    i = _TAG2IDX.get(tag)
    return None if i is None else LADDER[i]


def extend_level(tag):
    """0 inside the base grid, k>0 for the k-th rung outside it, None if off-ladder."""
    i = _TAG2IDX.get(tag)
    if i is None:
        return None
    if I_LO <= i <= I_HI:
        return 0
    return I_LO - i if i < I_LO else i - I_HI


def neighbour_tag(tag, direction):
    i = _TAG2IDX.get(tag)
    if i is None:
        return None
    j = i + (1 if direction > 0 else -1)
    return LADDER_TAGS[j] if 0 <= j < len(LADDER_TAGS) else None


# ---------------------------------------------------------------- tag / path conventions
def _detect_window_flag():
    """Which run_m3.py flag carries the TBPTT window.

    Package A's A10 item adds `--tbptt_window`; until it lands `--tbptt_k` *is* the
    window (run_m3.py: `if win_len >= args.tbptt_k`), so the supplements do not depend
    on A10 -- we simply name the flag that exists in the runner we can see.
    """
    try:
        src = open(os.path.join(HERE, "run_m3.py"), encoding="utf-8", errors="replace").read()
    except OSError:
        return "tbptt_k", None
    flag = "tbptt_window" if re.search(r"--tbptt_window", src) else "tbptt_k"
    m = re.search(r'"--tbptt_k"[^)]*?default=(\d+)', src)
    return flag, (int(m.group(1)) if m else None)


WINDOW_FLAG, _detected_default = _detect_window_flag()
if _detected_default is not None and _detected_default != TBPTT_DEFAULT_WINDOW:
    print("[warn] run_m3.py --tbptt_k default is %s, this script assumed %s; bare TBPTT "
          "tags now mean window %s"
          % (_detected_default, TBPTT_DEFAULT_WINDOW, _detected_default), file=sys.stderr)
    TBPTT_DEFAULT_WINDOW = _detected_default


def is_tbptt(algo):
    return bool(algo) and (algo in TBPTT_ALGOS or algo.startswith("tbptt"))


def tag_for(algo, lrtag, window):
    """Filename tag.

    Bare `lrNe-NN` whenever the window is the run_m3 default, so the tags of the stage-1
    grid already emitted by make_r2_jobs.py are reproduced byte-for-byte; `lrNe-NN_w<W>`
    for any other TBPTT window.  If package A later grows its own `tbptt_tag(lr, w)`
    helper we defer to it.
    """
    hook = getattr(mj, "tbptt_tag", None)
    if is_tbptt(algo) and window is not None and callable(hook):
        return hook(lr_of_tag(lrtag), window)
    if is_tbptt(algo) and window is not None and int(window) != TBPTT_DEFAULT_WINDOW:
        return "%s_w%d" % (lrtag, int(window))
    return lrtag


def out_path(outdir, task, algo, seed, tag):
    """Same expression as make_r2_jobs.m3_job's `# out=` annotation."""
    return "%s/%s_%s_s%s_%s.json" % (outdir, task, algo, seed, tag)


def job_line(task, algo, seed, lrtag, window, steps, outdir):
    lr = lr_of_tag(lrtag)
    if lr is None:
        raise SystemExit("cannot map tag %r back to a learning rate" % lrtag)
    extra = ""
    if is_tbptt(algo) and window is not None:
        extra = "--%s %d" % (WINDOW_FLAG, int(window))
    return mj.m3_job(task, algo, seed, lr, steps, outdir,
                     tag_for(algo, lrtag, window), svd_driver="auto", shadow=1, extra=extra)


def expected_windows(algo):
    return list(TBPTT_WINDOWS) if is_tbptt(algo) else [None]


# ---------------------------------------------------------------- metric direction check
def loss_types_from_source(path):
    """Map task name -> loss_type by parsing skrtrl/tasks.py (no torch import)."""
    tree = ast.parse(open(path, encoding="utf-8").read())
    lt, bases, factories = {}, {}, {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            bases[node.name] = [b.id for b in node.bases if isinstance(b, ast.Name)]
            for st in node.body:
                if (isinstance(st, ast.Assign) and len(st.targets) == 1
                        and isinstance(st.targets[0], ast.Name)
                        and st.targets[0].id == "loss_type"
                        and isinstance(st.value, ast.Constant)):
                    lt[node.name] = st.value.value
        elif isinstance(node, ast.FunctionDef):
            for st in ast.walk(node):
                if (isinstance(st, ast.Return) and isinstance(st.value, ast.Call)
                        and isinstance(st.value.func, ast.Name)):
                    factories[node.name] = st.value.func.id

    def resolve(name, depth=0):
        if depth > 10:
            return None
        if name in factories:
            name = factories[name]
        if name in lt:
            return lt[name]
        for b in bases.get(name, []):
            r = resolve(b, depth + 1)
            if r:
                return r
        return None

    out = {}
    for node in ast.walk(tree):
        if (isinstance(node, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id == "TASKS" for t in node.targets)
                and isinstance(node.value, ast.Dict)):
            for k, v in zip(node.value.keys, node.value.values):
                if isinstance(k, ast.Constant) and isinstance(v, ast.Name):
                    out[k.value] = resolve(v.id)
    return out


def cmd_verify_direction(args):
    path = rel(args.tasks_py)
    got = loss_types_from_source(path)
    ce = {t for t in TASKS if got.get(t) == "ce"}
    unknown = [t for t in TASKS if got.get(t) is None]
    print("parsed %s" % path)
    for t in TASKS:
        d = "higher-is-better (accuracy)" if t in HIGHER_IS_BETTER else "lower-is-better (MSE)"
        print("  %-12s loss_type=%-4s  ->  %s" % (t, got.get(t), d))
    ok = (ce == HIGHER_IS_BETTER) and not unknown
    if unknown:
        print("[FAIL] loss_type not resolvable for: %s" % unknown)
    if ce != HIGHER_IS_BETTER:
        print("[FAIL] source says ce=%s, table says higher-is-better=%s"
              % (sorted(ce), sorted(HIGHER_IS_BETTER)))
    print("direction table %s" % ("OK" if ok else "MISMATCH"))
    return 0 if ok else 1


# ---------------------------------------------------------------- run parsing / scoring
def window_score(records, steps, frac):
    lo = frac * float(steps or 0)
    vals = [r.get("metric") for r in records
            if isinstance(r.get("step"), (int, float)) and r["step"] >= lo]
    vals = [v for v in vals if isinstance(v, (int, float))]
    if not vals:
        return None, 0, lo
    return sum(vals) / len(vals), len(vals), lo


def read_run(path, frac):
    rec = {"path": path, "file": os.path.basename(path), "status": "ok"}
    try:
        with open(path, encoding="utf-8") as fh:
            d = json.load(fh)
    except Exception as e:                                          # noqa: BLE001
        rec.update(status="unreadable", error="%s: %s" % (type(e).__name__, e))
        return rec
    if not isinstance(d, dict):
        rec.update(status="unreadable", error="top level is not an object")
        return rec
    a = d.get("args") or {}
    records = d.get("records") or []
    rec.update(task=a.get("task"), algo=a.get("algo"), seed=a.get("seed"), lr=a.get("lr"),
               steps=a.get("steps"), tag=a.get("tag"), n_records=len(records))
    if is_tbptt(rec["algo"] or ""):
        w = a.get("tbptt_window", a.get("tbptt_k"))
        rec["window"] = int(w) if isinstance(w, (int, float)) else None
    else:
        rec["window"] = None
    if None in (rec["task"], rec["algo"], rec["seed"], rec["lr"]):
        rec.update(status="bad_args", error="args missing task/algo/seed/lr")
        return rec
    rec["seed"] = int(rec["seed"])
    rec["lrtag"] = mj.lr_tag(float(rec["lr"]))
    last = records[-1].get("metric") if records else None
    rec["last_metric"] = last if isinstance(last, (int, float)) else None
    if not records:
        rec.update(status="no_records", score=None, n_window=0)
        return rec
    s, n, lo = window_score(records, rec["steps"], frac)
    rec.update(n_window=n, window_lo=lo, score=s)
    if s is None:
        rec["status"] = "window_empty"
    elif not math.isfinite(s):
        rec["status"] = "diverged"
    return rec


def scan_dir(indir, frac, tasks=None, algos=None):
    runs, problems = [], []
    if not os.path.isdir(indir):
        return runs, problems
    for fn in sorted(os.listdir(indir)):
        if not fn.endswith(".json"):
            continue
        r = read_run(os.path.join(indir, fn), frac)
        if r["status"] in ("unreadable", "bad_args"):
            problems.append(r)
            continue
        if tasks and r["task"] not in tasks:
            continue
        if algos and r["algo"] not in algos:
            continue
        runs.append(r)
    return runs, problems


def key_of(score, higher_better):
    """Ranking key -- always "smaller is better"; unusable/diverged ranks last."""
    if score is None or not isinstance(score, (int, float)) or not math.isfinite(score):
        return math.inf
    return -score if higher_better else score


def usable(r, allow_fallback):
    if r["status"] in ("ok", "diverged"):
        return True                     # diverged is evidence: it competes and ranks last
    if r["status"] == "window_empty" and allow_fallback and r.get("last_metric") is not None:
        return True
    return False


def effective_score(r, allow_fallback):
    if r["status"] in ("ok", "diverged"):
        return r["score"]
    if r["status"] == "window_empty" and allow_fallback:
        return r.get("last_metric")
    return None


# ---------------------------------------------------------------- selection
def select(runs, stage, seeds, allow_partial, allow_fallback, tie_rtol, max_extend,
           restrict=None):
    """restrict: {(task, algo): [(lrtag, window), ...]} -- stage-2 candidate whitelist."""
    by_pair = {}
    for r in runs:
        by_pair.setdefault((r["task"], r["algo"]), {}) \
               .setdefault((r["lrtag"], r["window"]), {})[r["seed"]] = r

    def cfg_sort(key):
        lrtag, window = key
        return (_TAG2IDX.get(lrtag, 10 ** 6), -1 if window is None else window)

    pairs = []
    for task in TASKS:
        higher = task in HIGHER_IS_BETTER
        for algo in ALGOS:
            cands_raw = by_pair.get((task, algo), {})
            allowed = None
            if restrict is not None:
                allowed = {(t, None if w is None else int(w))
                           for t, w in restrict.get((task, algo), [])}
            cands = []
            for key in sorted(cands_raw, key=cfg_sort):
                lrtag, window = key
                per_seed = cands_raw[key]
                off_protocol = allowed is not None and key not in allowed
                seed_scores, flags = {}, []
                for sd in seeds:
                    r = per_seed.get(sd)
                    if r is None:
                        continue
                    if r["status"] != "ok":
                        flags.append("%s(s%s)" % (r["status"], sd))
                    if usable(r, allow_fallback):
                        seed_scores[sd] = effective_score(r, allow_fallback)
                n = len(seed_scores)
                mean = (sum(seed_scores.values()) / n) if n else None
                complete = (n == len(seeds))
                eligible = bool((complete or (allow_partial and n > 0)) and not off_protocol)
                cands.append({
                    "lrtag": lrtag, "lr": lr_of_tag(lrtag), "window": window,
                    "tag": tag_for(algo, lrtag, window),
                    "seed_scores": {str(k): v for k, v in seed_scores.items()},
                    "score": mean, "n_seeds": n, "complete": complete, "eligible": eligible,
                    "off_protocol": off_protocol, "extend_level": extend_level(lrtag),
                    "flags": flags, "extra_seeds": sorted(set(per_seed) - set(seeds)),
                    "seeds_present": sorted(per_seed),
                    "key": key_of(mean, higher) if eligible else math.inf,
                })

            ranked = sorted([c for c in cands if c["eligible"]],
                            key=lambda c: (c["key"], _TAG2IDX.get(c["lrtag"], 10 ** 6),
                                           -1 if c["window"] is None else c["window"]))
            sel = ranked[0] if ranked else None
            ties = []
            if sel is not None and math.isfinite(sel["key"]):
                kb = sel["key"]
                ties = [c["tag"] for c in ranked[1:]
                        if abs(c["key"] - kb) <= tie_rtol * max(1.0, abs(kb))]
            top = [{"lrtag": c["lrtag"], "lr": c["lr"], "window": c["window"],
                    "tag": c["tag"], "score": c["score"]} for c in ranked[:TOP_K_STAGE2]]
            pairs.append({
                "task": task, "algo": algo,
                "direction": "higher_is_better" if higher else "lower_is_better",
                "candidates": cands, "n_eligible": len(ranked),
                "selected": None if sel is None else
                            {"lrtag": sel["lrtag"], "lr": sel["lr"], "window": sel["window"],
                             "tag": sel["tag"], "score": sel["score"],
                             "extend_level": sel["extend_level"]},
                "ties_with_selected": ties, "top2": top,
                "boundary": (boundary_of(cands, sel, max_extend) if stage == 1
                             else informational_edge(sel)),
            })
    return pairs


def boundary_of(cands, sel, max_extend):
    """Stage-1 boundary rule: extend the grid one rung outwards, at most `max_extend`."""
    b = {"at": None, "reason": None, "next_lrtag": None, "next_lr": None,
         "next_level": None, "exhausted": False, "action": "none"}
    if sel is None:
        b["reason"] = "no eligible candidate yet"
        return b
    win = sel["window"]
    complete_tags = {c["lrtag"] for c in cands
                     if c["window"] == win and c["complete"] and not c["off_protocol"]}
    base_needed = {mj.lr_tag(l) for l in BASE_LRS}
    if not base_needed.issubset(complete_tags):
        b["reason"] = ("base grid incomplete for this pair%s (%d/%d LRs have both seeds)"
                       % ("" if win is None else "/window %s" % win,
                          len(complete_tags & base_needed), len(base_needed)))
        return b
    idxs = sorted(_TAG2IDX[t] for t in complete_tags if t in _TAG2IDX)
    i_sel = _TAG2IDX.get(sel["lrtag"])
    if i_sel is None:
        b["reason"] = "selected LR is off the 1-3 ladder"
        return b
    if i_sel == min(idxs):
        b["at"], direction = "lower", -1
    elif i_sel == max(idxs):
        b["at"], direction = "upper", +1
    else:
        b["reason"] = "interior optimum"
        return b
    nxt = neighbour_tag(sel["lrtag"], direction)
    lvl = extend_level(nxt) if nxt else None
    if nxt is None or lvl is None or lvl > max_extend:
        b["exhausted"] = True
        b["reason"] = ("winner at the %s edge but the extension cap (%d) is reached"
                       % (b["at"], max_extend))
        return b
    b.update(next_lrtag=nxt, next_lr=lr_of_tag(nxt), next_level=lvl, action="extend",
             reason="winner at the %s edge of the explored grid" % b["at"])
    return b


def informational_edge(sel):
    if sel is None:
        return {"at": None, "action": "none", "exhausted": False,
                "reason": "no eligible candidate yet"}
    return {"at": None, "action": "none", "exhausted": False,
            "reason": "stage-2 winner is the final LR (no further extension); "
                      "extend_level=%s" % sel.get("extend_level")}


# ---------------------------------------------------------------- missing runs
def expected_stage1(tasks, algos):
    outdir, exp = DEFAULT_DIRS[1], []
    for task in tasks:
        for algo in algos:
            for w in expected_windows(algo):
                for l in BASE_LRS:
                    lrtag = mj.lr_tag(l)
                    for sd in SEEDS_TUNE:
                        exp.append((task, algo, lrtag, w, sd,
                                    out_path(outdir, task, algo, sd, tag_for(algo, lrtag, w))))
    return exp


def missing_for_pairs(pairs, indir, stage, seeds, restrict=None):
    """Attach a per-pair `missing` list; return the flat list as well."""
    flat = []
    outdir_rel = indir if os.path.isabs(indir) else indir
    try:
        r = os.path.relpath(rel(indir), HERE).replace("\\", "/")
        if not r.startswith(".."):
            outdir_rel = r
    except ValueError:
        pass
    for e in pairs:
        task, algo = e["task"], e["algo"]
        want = []
        if stage == 1:
            for w in expected_windows(algo):
                for l in BASE_LRS:
                    want.append((mj.lr_tag(l), w))
            for c in e["candidates"]:                     # partially-present extensions
                if (c["extend_level"] or 0) > 0:
                    want.append((c["lrtag"], c["window"]))
            b = e.get("boundary") or {}
            if b.get("action") == "extend":               # the extension we are about to emit
                want.append((b["next_lrtag"], (e["selected"] or {}).get("window")))
        else:
            want = list((restrict or {}).get((task, algo), []))
            if not want:
                want = sorted({(c["lrtag"], c["window"]) for c in e["candidates"]})
        seen = {(c["lrtag"], c["window"]): c for c in e["candidates"]}
        miss = []
        for lrtag, w in sorted(set(want), key=lambda k: (_TAG2IDX.get(k[0], 10 ** 6),
                                                         -1 if k[1] is None else k[1])):
            c = seen.get((lrtag, w))
            have = set(c["seeds_present"]) if c else set()
            for sd in seeds:
                if sd in have:
                    continue
                p = out_path(outdir_rel, task, algo, sd, tag_for(algo, lrtag, w))
                miss.append({"lrtag": lrtag, "window": w, "seed": sd, "expected_out": p,
                             "extension": bool(extend_level(lrtag))})
                flat.append((task, algo, lrtag, w, sd, p))
        e["missing"] = miss
    return flat


# ---------------------------------------------------------------- reporting
def fmt(x, nd=6):
    if x is None or not isinstance(x, (int, float)):
        return "--"
    if isinstance(x, float):
        if x != x:
            return "nan"
        if not math.isfinite(x):
            return "inf" if x > 0 else "-inf"
    return ("%." + str(nd) + "g") % x


def cfg_label(c):
    return c["lrtag"] if c.get("window") is None else "%s/w%s" % (c["lrtag"], c["window"])


def write_report(pairs, problems, meta, md_path, json_path):
    d = os.path.dirname(md_path)
    if d:
        os.makedirs(d, exist_ok=True)
    stage, seeds = meta["stage"], meta["seeds"]
    pct = round((1.0 - meta["frac"]) * 100)       # "last 20 %" for frac = 0.8
    L = ["# D4 learning-rate selection -- stage %d" % stage, "",
         "Generated %s by `code/make_r2_d4_select.py select --stage %d`."
         % (meta["generated"], stage), "",
         "- input directory: `%s`" % meta["indir"],
         "- score per run: mean `metric` over records with `step >= %g * args.steps` "
         "(last %d%% window)" % (meta["frac"], pct),
         "- score per config: unweighted mean over tuning seeds %s (the seed is the unit)"
         % seeds,
         "- metric direction: accuracy, higher is better for %s; MSE, lower is better for "
         "every other D4 task" % ", ".join(sorted(HIGHER_IS_BETTER)),
         "- ties: broken towards the smaller LR, then the smaller TBPTT window "
         "(relative tolerance %g)" % meta["tie_rtol"]]
    if stage == 1:
        L.append("- boundary rule: a winner at the edge of the explored grid extends the "
                 "grid one rung on the 1-3 ladder, at most %d times" % meta["max_extend"])
    L += ["- configs with only one tuning seed: %s"
          % ("eligible (--allow-partial)" if meta["allow_partial"] else "not eligible"),
          "- runs with no record inside the last %d%%: %s" % (
              pct, "the last record is used (--allow-window-fallback)"
              if meta["allow_window_fallback"] else "treated as unusable"),
          "- TBPTT window grid %s, window flag `--%s`, bare tag means window %s"
          % (meta["tbptt_windows"], meta["window_flag"], meta["tbptt_default_window"]), ""]

    L += ["## Summary -- selected configuration per (task, estimator)", "",
          "| task | " + " | ".join(ALGOS) + " |", "|" + "---|" * (len(ALGOS) + 1)]
    index = {(p["task"], p["algo"]): p for p in pairs}
    for task in TASKS:
        cells = []
        for algo in ALGOS:
            e = index.get((task, algo))
            if e is None or not e["selected"]:
                cells.append("--")
                continue
            lab = cfg_label(e["selected"])
            b = e.get("boundary") or {}
            if b.get("action") == "extend":
                lab += " (B)"
            elif b.get("exhausted"):
                lab += " (B!)"
            if e["ties_with_selected"]:
                lab += " (=)"
            cells.append(lab)
        L.append("| %s | %s |" % (task, " | ".join(cells)))
    L += ["", "`(B)` boundary, extension emitted; `(B!)` boundary but the extension cap is "
          "reached; `(=)` tied with another config.", ""]

    n_sel = sum(1 for p in pairs if p["selected"])
    n_ext = sum(1 for p in pairs if (p.get("boundary") or {}).get("action") == "extend")
    n_exh = sum(1 for p in pairs if (p.get("boundary") or {}).get("exhausted"))
    n_miss = sum(len(p.get("missing", [])) for p in pairs)
    L += ["## Counts", "", "| quantity | value |", "|---|---|",
          "| (task, estimator) pairs | %d |" % len(pairs),
          "| pairs with a selection | %d |" % n_sel,
          "| pairs pending (no eligible config) | %d |" % (len(pairs) - n_sel),
          "| pairs at a grid boundary, extension emitted | %d |" % n_ext,
          "| pairs at a grid boundary, cap reached | %d |" % n_exh,
          "| pairs with fewer than %d eligible configs | %d |"
          % (TOP_K_STAGE2, sum(1 for p in pairs if p["n_eligible"] < TOP_K_STAGE2)),
          "| pairs with a tie at the top | %d |"
          % sum(1 for p in pairs if p["ties_with_selected"]),
          "| runs found | %d |" % meta["n_runs"],
          "| missing runs | %d |" % n_miss,
          "| unreadable / malformed files | %d |" % len(problems), ""]

    if problems:
        L += ["### Unreadable files", ""]
        L += ["- `%s`: %s" % (p["file"], p.get("error", p["status"])) for p in problems]
        L.append("")

    L += ["## Per-pair detail", ""]
    for e in pairs:
        L += ["### %s / %s" % (e["task"], e["algo"]), "",
              "direction: %s" % e["direction"], ""]
        if e["candidates"]:
            head = ["config", "lr"] + (["window"] if is_tbptt(e["algo"]) else []) \
                + ["s%s" % s for s in seeds] + ["seed-mean", "n", "rank", "flags"]
            L += ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
            ranked = sorted([c for c in e["candidates"] if c["eligible"]],
                            key=lambda c: (c["key"], _TAG2IDX.get(c["lrtag"], 10 ** 6),
                                           -1 if c["window"] is None else c["window"]))
            rank_of = {id(c): i + 1 for i, c in enumerate(ranked)}
            for c in e["candidates"]:
                row = [c["tag"], fmt(c["lr"], 3)]
                if is_tbptt(e["algo"]):
                    row.append("--" if c["window"] is None else str(c["window"]))
                row += [fmt(c["seed_scores"].get(str(s))) for s in seeds]
                row.append("**%s**" % fmt(c["score"]) if c["eligible"] else fmt(c["score"]))
                row.append("%d/%d" % (c["n_seeds"], len(seeds)))
                row.append(str(rank_of.get(id(c), "--")))
                fl = list(c["flags"])
                if (c["extend_level"] or 0) > 0:
                    fl.append("ext-L%d" % c["extend_level"])
                if c["off_protocol"]:
                    fl.append("off-protocol")
                if not c["eligible"]:
                    fl.append("not-eligible")
                if c["extra_seeds"]:
                    fl.append("extra-seeds=%s" % c["extra_seeds"])
                row.append(", ".join(fl))
                L.append("| " + " | ".join(row) + " |")
            L.append("")
        else:
            L += ["_no runs found_", ""]
        if e["selected"]:
            s = e["selected"]
            L.append("- **selected**: `%s` (lr %s%s), seed-mean %s"
                     % (s["tag"], fmt(s["lr"], 3),
                        "" if s["window"] is None else ", window %s" % s["window"],
                        fmt(s["score"])))
        else:
            L.append("- **selected**: pending")
        if e["top2"]:
            L.append("- top-%d for stage 2: %s"
                     % (TOP_K_STAGE2, ", ".join("`%s` (%s)" % (c["tag"], fmt(c["score"]))
                                                for c in e["top2"])))
        if e["ties_with_selected"]:
            L.append("- tied with the winner: %s (tie broken towards the smaller LR)"
                     % ", ".join("`%s`" % t for t in e["ties_with_selected"]))
        b = e.get("boundary") or {}
        if b.get("action") == "extend":
            L.append("- **boundary**: %s -> extend to `%s` (lr %s, level %d of %d)"
                     % (b["reason"], b["next_lrtag"], fmt(b["next_lr"], 3),
                        b["next_level"], meta["max_extend"]))
        elif b.get("exhausted"):
            L.append("- **boundary**: %s -- no further extension" % b["reason"])
        elif b.get("reason"):
            L.append("- boundary: %s" % b["reason"])
        if e.get("missing"):
            L.append("- missing runs (%d):" % len(e["missing"]))
            for m in e["missing"]:
                L.append("  - `%s`%s" % (m["expected_out"],
                                         " [extension]" if m["extension"] else ""))
        L.append("")

    with open(md_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")

    def clean(o):
        if isinstance(o, float):
            return o if math.isfinite(o) else None
        if isinstance(o, dict):
            return {k: clean(v) for k, v in o.items()}
        if isinstance(o, list):
            return [clean(v) for v in o]
        return o

    payload = {"meta": meta, "pairs": clean(pairs),
               "problems": [{k: v for k, v in p.items() if k != "path"} for p in problems]}
    with open(json_path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(payload, fh, indent=1)
    return md_path, json_path


# ---------------------------------------------------------------- sub-commands
def _restrict_from_stage1(path):
    """{(task, algo): [(lrtag, window), ...]} = the top-2 chosen at stage 1."""
    if not os.path.exists(path):
        return None
    d = json.load(open(path, encoding="utf-8"))
    out = {}
    for e in d.get("pairs", []):
        top = [(c["lrtag"], c["window"]) for c in e.get("top2", [])]
        if top:
            out[(e["task"], e["algo"])] = top
    return out or None


def cmd_select(args):
    stage = args.stage
    indir = rel(args.indir or DEFAULT_DIRS[stage])
    tasks = [t for t in TASKS if not args.tasks or t in args.tasks.split(",")]
    algos = [a for a in ALGOS if not args.algos or a in args.algos.split(",")]
    runs, problems = scan_dir(indir, args.frac, set(tasks), set(algos))

    restrict = None
    if stage == 2 and not args.no_restrict:
        restrict = _restrict_from_stage1(os.path.join(rel(args.outdir),
                                                      "D4_SELECT_stage1.json"))
        if restrict is None:
            print("[warn] no D4_SELECT_stage1.json in %s -- stage-2 candidates are taken "
                  "from the directory as-is and the missing list is best-effort"
                  % rel(args.outdir), file=sys.stderr)

    pairs_all = select(runs, stage, SEEDS_TUNE, args.allow_partial,
                       args.allow_window_fallback, args.tie_rtol, args.max_extend, restrict)
    pairs = [p for p in pairs_all if p["task"] in tasks and p["algo"] in algos]
    missing_for_pairs(pairs, args.indir or DEFAULT_DIRS[stage], stage, SEEDS_TUNE, restrict)

    meta = {"stage": stage, "indir": indir.replace("\\", "/"),
            "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "frac": args.frac, "seeds": SEEDS_TUNE,
            "steps_expected": STEPS_TUNE if stage == 1 else STEPS_STAGE2,
            "tie_rtol": args.tie_rtol, "max_extend": args.max_extend,
            "allow_partial": bool(args.allow_partial),
            "allow_window_fallback": bool(args.allow_window_fallback),
            "higher_is_better": sorted(HIGHER_IS_BETTER), "base_lrs": BASE_LRS,
            "tbptt_windows": TBPTT_WINDOWS, "window_flag": WINDOW_FLAG,
            "tbptt_default_window": TBPTT_DEFAULT_WINDOW,
            "tasks": tasks, "algos": algos,
            "n_runs": len(runs), "n_pairs": len(pairs),
            "restricted_to_stage1_top2": bool(restrict)}
    outdir = rel(args.outdir)
    md = os.path.join(outdir, "D4_SELECT_stage%d.md" % stage)
    js = os.path.join(outdir, "D4_SELECT_stage%d.json" % stage)
    write_report(pairs, problems, meta, md, js)

    n_sel = sum(1 for p in pairs if p["selected"])
    n_ext = sum(1 for p in pairs if (p.get("boundary") or {}).get("action") == "extend")
    n_miss = sum(len(p.get("missing", [])) for p in pairs)
    print("stage %d: %d runs parsed from %s" % (stage, len(runs), meta["indir"]))
    print("  pairs %d | selected %d | pending %d | boundary-extend %d | missing runs %d"
          % (len(pairs), n_sel, len(pairs) - n_sel, n_ext, n_miss))
    if problems:
        print("  unreadable/malformed files: %d (%s)"
              % (len(problems), ", ".join(p["file"] for p in problems[:4])))
    print("wrote %s" % md)
    print("wrote %s" % js)
    return 0


def cmd_emit(args):
    what = args.what
    stage_json = args.sel_json or os.path.join(args.outdir, "D4_SELECT_stage%d.json"
                                               % (2 if what == "eval" else 1))
    stage_json = rel(stage_json)
    if not os.path.exists(stage_json):
        raise SystemExit("%s not found -- run `select --stage %d` first"
                         % (stage_json, 2 if what == "eval" else 1))
    d = json.load(open(stage_json, encoding="utf-8"))
    pairs = {(e["task"], e["algo"]): e for e in d.get("pairs", [])}
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    src = os.path.basename(stage_json)
    head, notes, body = [], [], []

    if what == "boundary":
        outdir = DEFAULT_DIRS[1]
        head += ["# D4 stage-1 supplements, generated %s from %s" % (stamp, src),
                 "# LR-grid extensions (one rung on the 1-3 ladder, cap %d) plus the TBPTT "
                 "window fill; %d steps, tuning seeds %s, shadow on, svd_driver auto"
                 % (args.max_extend, STEPS_TUNE, SEEDS_TUNE),
                 "# written to the same directory as the screen (%s), so `select --stage 1` "
                 "picks them up automatically" % outdir]
        plan = {}          # (task, algo) -> [(lrtag, window, why)]
        for (task, algo), e in pairs.items():
            b = e.get("boundary") or {}
            if b.get("action") == "extend" and b.get("next_lrtag"):
                plan.setdefault((task, algo), []).append(
                    (b["next_lrtag"], (e.get("selected") or {}).get("window"), "boundary"))
        if not args.no_tbptt_fill:
            for task in TASKS:
                for algo in ALGOS:
                    if not is_tbptt(algo):
                        continue
                    e = pairs.get((task, algo)) or {}
                    have = {(c["lrtag"], c["window"]) for c in e.get("candidates", [])
                            if c.get("complete")}
                    for w in TBPTT_WINDOWS:
                        if w == TBPTT_DEFAULT_WINDOW:
                            continue
                        for l in BASE_LRS:
                            t = mj.lr_tag(l)
                            if (t, w) not in have:
                                plan.setdefault((task, algo), []).append((t, w, "window-fill"))
        n_b = sum(1 for v in plan.values() for c in v if c[2] == "boundary")
        n_w = sum(1 for v in plan.values() for c in v if c[2] == "window-fill")
        notes.append("# %d LR-extension config(s), %d TBPTT window-fill config(s), "
                     "x %d seeds" % (n_b, n_w, len(SEEDS_TUNE)))
        for task in TASKS:
            for seed in SEEDS_TUNE:
                for algo in ALGOS:
                    for lrtag, w, _why in plan.get((task, algo), []):
                        body.append(job_line(task, algo, seed, lrtag, w, STEPS_TUNE, outdir))

    elif what == "stage2":
        outdir = DEFAULT_DIRS[2]
        head += ["# D4 stage-2 tuning, generated %s from %s" % (stamp, src),
                 "# top-%d stage-1 LRs per (task, estimator) x seeds %s x %d steps, "
                 "shadow on, svd_driver auto" % (TOP_K_STAGE2, SEEDS_TUNE, STEPS_STAGE2),
                 "# final LR = best last-20%% window mean here (mean over the two seeds)"]
        skipped = set()
        for task in TASKS:
            for rank in range(TOP_K_STAGE2):
                for seed in SEEDS_TUNE:
                    for algo in ALGOS:
                        e = pairs.get((task, algo))
                        if not e:
                            continue
                        b = e.get("boundary") or {}
                        if b.get("action") == "extend" and not args.include_pending:
                            skipped.add("%s/%s" % (task, algo))
                            continue
                        top = e.get("top2") or []
                        if rank >= len(top):
                            continue
                        c = top[rank]
                        body.append(job_line(task, algo, seed, c["lrtag"], c["window"],
                                             STEPS_STAGE2, outdir))
        if skipped:
            notes.append("# withheld because a boundary extension is still pending "
                         "(re-run select+emit after the supplements land; --include-pending "
                         "overrides): %s" % ", ".join(sorted(skipped)))

    else:                                                                     # eval
        outdir = EVAL_DIR
        head += ["# D4 evaluation, generated %s from %s" % (stamp, src),
                 "# final LR per (task, estimator) x seeds %d-%d x %d steps, shadow on, "
                 "svd_driver auto" % (SEEDS_EVAL[0], SEEDS_EVAL[-1], STEPS_EVAL)]
        pend = set()
        for task in TASKS:
            for seed in SEEDS_EVAL:
                for algo in ALGOS:
                    e = pairs.get((task, algo))
                    if not e or not e.get("selected"):
                        pend.add("%s/%s" % (task, algo))
                        continue
                    s = e["selected"]
                    body.append(job_line(task, algo, seed, s["lrtag"], s["window"],
                                         STEPS_EVAL, outdir))
        if pend:
            notes.append("# no stage-2 winner yet, not emitted: %s" % ", ".join(sorted(pend)))

    out = rel(args.out or os.path.join(JOBS_DIR, JOB_FILES[what]))
    d_out = os.path.dirname(out)
    if d_out:
        os.makedirs(d_out, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(head + notes + body) + "\n")
    done = sum(1 for l in body if _out_of(l) and os.path.exists(rel(_out_of(l))))
    print("wrote %s: %d jobs (%d already have output -> the queue exists-skips them)"
          % (out, len(body), done))
    for n in notes:
        print("  " + n.lstrip("# "))
    return 0


_OUT_RE = re.compile(r"#\s*out\s*=\s*(\S+)\s*$")


def _out_of(line):
    m = _OUT_RE.search(line)
    return m.group(1) if m else None


def cmd_status(args):
    print("D4 status (relative paths are under %s)" % HERE)
    exp1 = expected_stage1(TASKS, ALGOS)
    have = sum(1 for row in exp1 if os.path.exists(rel(row[-1])))
    print("\n[stage 1 base grid]  %s" % DEFAULT_DIRS[1])
    print("  expected %d runs = %d tasks x %d algos x %d LRs x %d seeds "
          "(TBPTT counted over %d windows %s)"
          % (len(exp1), len(TASKS), len(ALGOS), len(BASE_LRS), len(SEEDS_TUNE),
             len(TBPTT_WINDOWS), TBPTT_WINDOWS))
    print("  present  %d   missing %d" % (have, len(exp1) - have))
    runs, problems = scan_dir(rel(DEFAULT_DIRS[1]), args.frac)
    ext = [r for r in runs if (extend_level(r["lrtag"]) or 0) > 0]
    print("  json parsed %d (LR-extension runs %d, unreadable/malformed %d)"
          % (len(runs), len(ext), len(problems)))
    bad = [r for r in runs if r["status"] != "ok"]
    if bad:
        print("  runs without a usable last-%d%% window: %d"
              % (round((1.0 - args.frac) * 100), len(bad)))
        for r in bad[:args.list_limit]:
            print("    %-54s %-13s records %-3s steps %s"
                  % (r["file"], r["status"], r["n_records"], r["steps"]))
        if len(bad) > args.list_limit:
            print("    ... %d more" % (len(bad) - args.list_limit))

    for label, sub in (("stage 2", DEFAULT_DIRS[2]), ("evaluation", EVAL_DIR)):
        p = rel(sub)
        rr, pp = scan_dir(p, args.frac)
        print("\n[%s]  %s%s" % (label, sub, "" if os.path.isdir(p) else "   [directory absent]"))
        print("  json parsed %d (unreadable/malformed %d)" % (len(rr), len(pp)))

    print("\n[job files]")
    for fn in ["d4_tune.txt"] + [JOB_FILES[k] for k in ("boundary", "stage2", "eval")]:
        p = rel(os.path.join(JOBS_DIR, fn))
        if not os.path.exists(p):
            print("  %-18s (absent)" % fn)
            continue
        n = ndone = nun = 0
        with open(p, encoding="utf-8") as fh:
            for line in fh:
                t = line.strip()
                if not t or t.startswith("#"):
                    continue
                n += 1
                o = _out_of(t)
                if o is None:
                    nun += 1
                elif os.path.exists(rel(o)):
                    ndone += 1
        print("  %-18s %4d jobs | done %4d | todo %4d%s"
              % (fn, n, ndone, n - ndone, "" if not nun else
                 " | %d line(s) without # out=" % nun))
    return 0


# ---------------------------------------------------------------- cli
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd")

    s = sub.add_parser("select", help="score runs and pick learning rates")
    s.add_argument("--stage", type=int, required=True, choices=[1, 2])
    s.add_argument("--indir", default=None,
                   help="default: %s (stage 1) / %s (stage 2)" % (DEFAULT_DIRS[1], DEFAULT_DIRS[2]))
    s.add_argument("--outdir", default=REPORT_DIR, help="where the report pair is written")
    s.add_argument("--frac", type=float, default=WINDOW_FRAC,
                   help="window start as a fraction of args.steps (default 0.8)")
    s.add_argument("--tie-rtol", type=float, default=1e-12)
    s.add_argument("--max-extend", type=int, default=MAX_EXTEND)
    s.add_argument("--allow-partial", action="store_true",
                   help="let a config compete with only one tuning seed")
    s.add_argument("--allow-window-fallback", action="store_true",
                   help="if no record falls inside the window, score the last record")
    s.add_argument("--no-restrict", action="store_true",
                   help="stage 2: do not restrict candidates to the stage-1 top-2")
    s.add_argument("--tasks", default="", help="comma-separated subset")
    s.add_argument("--algos", default="", help="comma-separated subset")
    s.set_defaults(func=cmd_select)

    e = sub.add_parser("emit", help="write a job file from a selection report")
    e.add_argument("--what", required=True, choices=["boundary", "stage2", "eval"])
    e.add_argument("--outdir", default=REPORT_DIR, help="where the selection json lives")
    e.add_argument("--sel-json", default=None, help="explicit selection json")
    e.add_argument("--out", default=None, help="explicit job-file path")
    e.add_argument("--max-extend", type=int, default=MAX_EXTEND,
                   help="documentation only; the cap is applied during select")
    e.add_argument("--no-tbptt-fill", action="store_true",
                   help="do not add the missing TBPTT non-default-window stage-1 jobs")
    e.add_argument("--include-pending", action="store_true",
                   help="stage2: emit pairs whose boundary extension has not run yet")
    e.set_defaults(func=cmd_emit)

    t = sub.add_parser("status", help="completion counts per stage")
    t.add_argument("--frac", type=float, default=WINDOW_FRAC)
    t.add_argument("--list-limit", type=int, default=12)
    t.set_defaults(func=cmd_status)

    v = sub.add_parser("verify-direction",
                       help="check the metric-direction table against skrtrl/tasks.py")
    v.add_argument("--tasks-py", default="skrtrl/tasks.py")
    v.set_defaults(func=cmd_verify_direction)

    args = ap.parse_args(argv)
    if not getattr(args, "func", None):
        ap.print_help()
        return 2
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
