"""E4b / D4b (R2, reviewer "astra" on D4): COMMON-TRAJECTORY estimator comparison.

Why this run exists
-------------------
In D4 every estimator trains its own network, so its gradient cosine against its own
exact shadow is measured on its *own* trajectory.  Two effects are then confounded:
(a) how accurate the estimator is, and (b) where its own training took the network.
The reviewer asked for the two to be separated.  Here they are: ONE trajectory is
generated by exact RTRL, and every estimator is attached to it as a **passive tracker**
that receives exactly the same (A_t, imm_t, delta_t) and exactly the same lane resets
and never contributes to a parameter update.  Any difference in grad_cos is then a
property of the estimator alone.

Protocol (identical trajectory conventions to run_e1_spectrum.py)
-----------------------------------------------------------------
* trainer         : OnlineLearner(..., "exact") -- exact RTRL updates W, U, b and the
                    readout; the "independent reference trajectory" convention of D1.
* passive trackers: SK-RTRL r in {4, 16, 32}, SnAp-1, UORO, KF-RTRL, RFLO, each built on
                    the SAME cell object, so every tracker sees the post-update W of the
                    single shared trajectory.  step_state() is called with the trainer's
                    (A_t, imm_t); lane resets are applied to every tracker in the same
                    step as the trainer's (see `reset_tracker_lanes`).
* TBPTT is **not applicable**: it is not an online estimator with a per-step state, it
                    produces one windowed autograd gradient at window end, so there is no
                    per-step ghat_t to compare against g_t.  Recorded in meta as such.

Per-step instrumentation (labelled steps only -- delta_t exists only where the task
emits a target), stride `--cert_every`:
    per tracker   grad_cos(g, ghat), rel_err = ||g - ghat||_F / ||g||_F
    SK-RTRL/SnAp-1 additionally
                  e_t (certificate), ||E_t||_F = ||J_t - (S + L R^T)||_F,
                  bound_t = mean_b ||delta_b||_2 * e_b   (batch-consistent Theorem 1),
                  rho^g_t = bound_t / ||ghat_t||_F, direction-certifiable iff rho^g < 1
and the D2 online counters accumulated after `--cert_warmup`:
    n_steps, n_rel_lt1, n_rel_lt05, n_tight_le10, n_no_signal (+ the Theorem-1 /
    Lemma-1 violation counters, which must stay at 0).

Randomness: UORO and KF-RTRL draw Rademacher noise from the *global* torch RNG.  With
`--rng_isolate 1` (default) each stochastic tracker gets its own RNG stream, seeded from
`--tracker_seed_base` (default 1000 * seed), swapped in around its step_state.  So the
trackers are mutually independent and, importantly, the trajectory and every other
tracker are unchanged by which trackers are enabled (`--trackers` subsets stay
comparable).

Output: <outdir>/<task>_n<n>_s<seed>[_<tag>].json   (exists-skip)
  args, meta, curve (task metric), records (one entry per log point, per-tracker series),
  tail_summary (mean over the last `--tail_frac` of log points), cert (per tracker),
  wall_s, peak_MB, svd_stats.
"""
import argparse, inspect, json, math, os, time
import torch

from skrtrl.tasks import TASKS
from skrtrl.train import OnlineLearner, make_algo
from skrtrl.algos import SKRTRL, SVD_STATS, _svd_stats_reset

TS_TASKS = {"henon", "mackeyglass", "lorenz", "sunspot", "laser"}
DEFAULT_TRACKERS = "skrtrl-r4,skrtrl-r16,skrtrl-r32,snap1,uoro,kfrtrl,rflo"
STOCHASTIC = {"uoro", "kfrtrl"}          # draw from the global torch RNG every step
EPS = 1e-12


# --------------------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------------------
def cos(a, b):
    na, nb = a.norm(), b.norm()
    if na < 1e-12 or nb < 1e-12:
        return float("nan")
    return ((a * b).sum() / (na * nb)).item()


def _nanmean(xs):
    """Mean over the finite entries; None if there are none (inf/NaN are dropped)."""
    v = [x for x in xs if x is not None and math.isfinite(x)]
    return (sum(v) / len(v)) if v else None


def _sanitize(o):
    """Replace non-finite floats by None so the json stays strict-JSON parseable."""
    if isinstance(o, float):
        return o if math.isfinite(o) else None
    if isinstance(o, dict):
        return {k: _sanitize(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_sanitize(v) for v in o]
    return o


@torch.no_grad()
def reset_tracker_lanes(a, mask):
    """Zero the estimator state of the reset lanes -- mirrors OnlineLearner._reset_lanes
    exactly, so a tracker resets in the same step and the same way as the trainer."""
    if getattr(a, "J", None) is not None:
        a.J[mask] = 0.0
    for attr in ("S", "L", "R"):
        t = getattr(a, attr, None)
        if t is not None and t.numel():
            t[mask] = 0.0
    if getattr(a, "e", None) is not None:
        a.e[mask] = 0.0
    if hasattr(a, "reset_lanes"):
        a.reset_lanes(mask)


class RngSlot:
    """A private RNG stream for one stochastic tracker.

    `with slot:` installs the slot's state as the ambient generator state, and on exit
    stores the advanced state back into the slot and restores the ambient state.  The
    trainer's stream and the other trackers' streams are therefore untouched.
    """

    def __init__(self, device, seed):
        self.cuda = torch.device(device).type == "cuda"
        self.dev = torch.device(device) if self.cuda else None
        amb = self._get()
        if self.cuda:
            with torch.cuda.device(self.dev):
                torch.cuda.manual_seed(seed)
        else:
            torch.manual_seed(seed)
        self.state = self._get()
        self._set(amb)
        self._amb = None

    def _get(self):
        return torch.cuda.get_rng_state(self.dev) if self.cuda else torch.get_rng_state()

    def _set(self, s):
        if self.cuda:
            torch.cuda.set_rng_state(s, self.dev)
        else:
            torch.set_rng_state(s)

    def __enter__(self):
        self._amb = self._get()
        self._set(self.state)
        return self

    def __exit__(self, *exc):
        self.state = self._get()
        self._set(self._amb)
        self._amb = None
        return False


class _Null:
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


# --------------------------------------------------------------------------------------
# D2-style online counters (same definitions as run_m3.CertCounters, kept local so this
# script never depends on run_m3 being importable / unchanged; `n_no_signal` is the
# explicit version of run_m3's implicit "ghat_norm == 0 is never counted as informative")
# --------------------------------------------------------------------------------------
class CertCounters:
    """rho^g_t = bound_t / ||ghat_t||_F  with  bound_t = mean_b ||delta_b||_2 * e_b.

    (i)  rho^g_t < 1   -> direction-certifiable without a shadow (also < 0.5)
    (ii) T_t = e_t / ||E_t||_F <= 10 -> certificate tight (needs the shadow)
    plus the Theorem-1 check ||g - ghat||_F <= bound_t and the Lemma-1 validity check
    ||E_t||_F <= e_t; both violation counters must stay at 0.
    """

    def __init__(self, has_shadow=True):
        self.has_shadow = has_shadow
        self.n_steps = 0
        self.n_no_signal = 0
        self.n_rel_lt1 = 0
        self.n_rel_lt05 = 0
        self.n_tight_checked = 0
        self.n_tight_finite = 0
        self.n_tight_inf = 0
        self.n_tight_le10 = 0
        self.n_bound_violation = 0
        self.n_bound_finite = 0
        self.n_bound_inf = 0
        self.n_rel_finite = 0
        self.n_rel_inf = 0
        self.n_cert_invalid = 0
        self.sum_rel = 0.0
        self.max_rel = 0.0
        self.sum_tight = 0.0
        self.max_tight = 0.0

    def update(self, bound, ghat_norm, gerr_norm, e_mean, trueE_mean,
               g_scale=0.0, e_scale=0.0):
        """g_scale / e_scale set the ABSOLUTE tolerance of the two validity tests.

        A tracker run at r >= n is the Corollary-3 exact path: e_t == 0 and E_t == 0
        analytically, while the measured ||g - ghat|| and ||E_t||_F are float32 round-off
        (~1e-6 of the gradient / of ||J_t||_F).  A purely relative test then reports every
        such step as a Theorem-1 / Lemma-1 violation.  The tests are therefore
            gerr  <= bound * (1 + 1e-4) + 1e-4 * g_scale
            trueE <= e_t   * (1 + 1e-4) + 1e-4 * e_scale
        with g_scale = max(||g||, ||ghat||) and e_scale = ||J_t||_F."""
        self.n_steps += 1
        if ghat_norm > EPS:
            rel = bound / ghat_norm
            # Without spectral clipping the certificate recursion e_t = rho_bar e_{t-1}
            # + eta_t has rho_bar ~ ||A||_F >> 1, so e_t saturates float32 within a few
            # tens of steps and rho^g_t is +inf.  Such steps are NOT informative; they
            # are counted separately so every mean below stays finite.
            if math.isfinite(rel):
                self.n_rel_finite += 1
                self.sum_rel += rel
                self.max_rel = max(self.max_rel, rel)
                if rel < 1.0:
                    self.n_rel_lt1 += 1
                if rel < 0.5:
                    self.n_rel_lt05 += 1
            else:
                self.n_rel_inf += 1
        else:
            self.n_no_signal += 1
        if gerr_norm is not None:
            if math.isfinite(bound):
                self.n_bound_finite += 1
                if gerr_norm > bound * (1.0 + 1e-4) + 1e-4 * g_scale:
                    self.n_bound_violation += 1
            else:
                self.n_bound_inf += 1
        if trueE_mean is not None:
            if (math.isfinite(e_mean)
                    and trueE_mean > e_mean * (1.0 + 1e-4) + 1e-4 * e_scale):
                self.n_cert_invalid += 1
            if trueE_mean > 1e-12:
                tight = e_mean / trueE_mean
                self.n_tight_checked += 1
                if math.isfinite(tight):
                    self.n_tight_finite += 1
                    self.sum_tight += tight
                    self.max_tight = max(self.max_tight, tight)
                else:
                    self.n_tight_inf += 1
                if tight <= 10.0:
                    self.n_tight_le10 += 1

    def summary(self):
        ns = max(self.n_steps, 1)
        nsig = max(self.n_steps - self.n_no_signal, 1)
        nt = max(self.n_tight_checked, 1)
        # frac_tight_le10 is over every checked step: an overflowed e_t is
        # a loose certificate, not a missing measurement.
        return {
            "n_steps": self.n_steps,
            "n_no_signal": self.n_no_signal,
            "n_rel_lt1": self.n_rel_lt1,
            "n_rel_lt05": self.n_rel_lt05,
            "n_tight_checked": self.n_tight_checked,
            "n_tight_finite": self.n_tight_finite,
            "n_tight_inf": self.n_tight_inf,
            "n_tight_le10": self.n_tight_le10,
            "n_bound_violation": self.n_bound_violation,
            "n_bound_finite": self.n_bound_finite,
            "n_bound_inf": self.n_bound_inf,
            "n_rel_finite": self.n_rel_finite,
            "n_rel_inf": self.n_rel_inf,
            "n_cert_invalid": self.n_cert_invalid,
            # over ALL counted steps (no-signal steps count against informativeness)
            "frac_rel_lt1": self.n_rel_lt1 / ns,
            "frac_rel_lt05": self.n_rel_lt05 / ns,
            # over the steps that carried a gradient signal
            "frac_rel_lt1_signal": self.n_rel_lt1 / nsig,
            "frac_rel_lt05_signal": self.n_rel_lt05 / nsig,
            "frac_tight_le10": (self.n_tight_le10 / nt) if self.n_tight_checked else None,
            "mean_rel_g": ((self.sum_rel / self.n_rel_finite)
                           if self.n_rel_finite else None),
            "max_rel_g": self.max_rel,
            "mean_tightness": ((self.sum_tight / self.n_tight_finite)
                               if self.n_tight_finite else None),
            "max_tightness": self.max_tight if self.n_tight_finite else None,
            "has_shadow": self.has_shadow,
            "cert_overflow_note": "n_rel_inf / n_bound_inf / n_tight_inf count steps "
                                  "whose certificate e_t had already overflowed float32 "
                                  "(rho_bar > 1 with no spectral clip); never counted as "
                                  "certifiable or tight",
            "violation_tol": "gerr <= bound*(1+1e-4) + 1e-4*max(||g||,||ghat||); "
                             "trueE <= e_t*(1+1e-4) + 1e-4*||J_t||_F",
            "delta_agg": "mean_b(||delta_b||_2 * e_b)",
            "counted_steps": "labelled steps with step >= cert_warmup and age >= "
                             "cert_min_age, stride cert_every",
        }


# --------------------------------------------------------------------------------------
class Tracker:
    """One passive estimator plus its per-log accumulators."""

    def __init__(self, name, algo, rng, has_cert):
        self.name = name
        self.algo = algo
        self.rng = rng                    # RngSlot | _Null
        self.has_cert = has_cert
        self.has_dense = hasattr(algo, "residual_dense")
        self.cert = CertCounters(has_shadow=self.has_dense) if has_cert else None
        self.clear()

    def clear(self):
        self.acc = {k: [] for k in ("grad_cos", "rel_err", "e_t", "trueE", "rho_g",
                                    "rho_g_inf", "rho_g_lt1", "ghat_norm", "bound",
                                    "tight")}

    def flush(self):
        rec = {}
        for k, v in self.acc.items():
            m = _nanmean(v)
            if m is not None:
                rec[k] = m
        rec["n_obs"] = len(self.acc["grad_cos"])
        self.clear()
        return rec


def build_trackers(names, cell, batch, device, seed_base, drv_kw, rng_isolate):
    out = []
    for i, name in enumerate(names):
        # make_algo forwards svd_driver only to the SK-RTRL family and drops it for the
        # stochastic/local baselines, so passing it unconditionally is safe.
        algo = make_algo(name, cell, batch, **drv_kw)
        rng = (RngSlot(device, seed_base + 17 * i)
               if (rng_isolate and name in STOCHASTIC) else _Null())
        out.append(Tracker(name, algo, rng, has_cert=hasattr(algo, "e")))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True, choices=list(TASKS))
    ap.add_argument("--n", type=int, default=64)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--steps", type=int, default=20000)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--log_every", type=int, default=250)
    ap.add_argument("--trackers", default=DEFAULT_TRACKERS,
                    help="comma list; default: " + DEFAULT_TRACKERS)
    ap.add_argument("--svd_driver", default="auto",
                    help='"" = leave the installed default; gesvd = kernel of record; '
                         'auto = default cuSOLVER driver first (same fallback chain)')
    ap.add_argument("--outdir", default="results/r2/e4b")
    ap.add_argument("--tag", default="")
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--clip", type=float, default=0.0)
    # time-series protocol, passed through exactly like run_m3.py / run_e1_spectrum.py
    ap.add_argument("--horizon", type=int, default=1)
    ap.add_argument("--causal", type=int, default=0)
    ap.add_argument("--washout", type=int, default=200)
    # D2 counters
    ap.add_argument("--cert_warmup", type=int, default=200)
    ap.add_argument("--cert_min_age", type=int, default=1)
    ap.add_argument("--cert_every", type=int, default=1)
    ap.add_argument("--tail_frac", type=float, default=0.2,
                    help="fraction of trailing log points averaged into tail_summary")
    ap.add_argument("--rng_isolate", type=int, default=1,
                    help="give each stochastic tracker its own RNG stream")
    ap.add_argument("--tracker_seed_base", type=int, default=-1,
                    help="-1 -> 1000 * seed")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    tag = f"_{args.tag}" if args.tag else ""
    out = f"{args.outdir}/{args.task}_n{args.n}_s{args.seed}{tag}.json"
    if os.path.exists(out):
        print("exists, skip:", out)
        return

    names = [s.strip() for s in args.trackers.split(",") if s.strip()]
    seed_base = args.seed * 1000 if args.tracker_seed_base < 0 else args.tracker_seed_base

    # svd_driver is threaded through only if the installed skrtrl supports it (another
    # agent owns algos.py/train.py; probe instead of assuming).
    drv_kw, drv_ok = {}, False
    if args.svd_driver:
        drv_ok = ("svd_driver" in inspect.signature(SKRTRL.__init__).parameters)
        if drv_ok:
            drv_kw = {"svd_driver": args.svd_driver}
        else:
            print(f"note: installed skrtrl has no svd_driver argument; --svd_driver="
                  f"{args.svd_driver} ignored")
    learner_kw = {}
    if drv_kw and "svd_driver" in inspect.signature(OnlineLearner.__init__).parameters:
        learner_kw = dict(drv_kw)

    _svd_stats_reset()
    if args.task in TS_TASKS:
        task = TASKS[args.task](args.batch, args.device, seed=args.seed,
                                horizon=args.horizon, causal=bool(args.causal),
                                washout=args.washout)
        period = args.washout
    else:
        task = TASKS[args.task](args.batch, args.device, seed=args.seed)
        period = int(getattr(task, "T", 0) or 0)

    # exact-RTRL trainer: the single shared trajectory
    learner = OnlineLearner(task, args.n, "exact", lr=args.lr, device=args.device,
                            seed=args.seed, spectral_clip=args.clip, **learner_kw)
    cell = learner.cell
    trackers = build_trackers(names, cell, task.B, args.device, seed_base, drv_kw,
                              bool(args.rng_isolate))
    n, p = cell.n, cell.p

    log = {
        "args": vars(args),
        "meta": {
            "P": n * p, "p": p, "n_in": task.n_in, "n_out": task.n_out,
            "reset_period": period, "train_algo": "exact",
            "trackers": names,
            "tracker_seed_base": seed_base,
            "svd_driver_applied": args.svd_driver if drv_ok else None,
            "protocol": "common trajectory: exact RTRL trains; all estimators are "
                        "passive trackers fed the same (A_t, imm_t, delta_t) and the "
                        "same lane resets; no tracker updates any parameter",
            "tbptt": "not applicable -- TBPTT is not an online per-step estimator "
                     "(one windowed autograd gradient at window end), so no per-step "
                     "ghat_t exists on a common trajectory; see D4 for its task metric",
            "stochastic_trackers": sorted(set(names) & STOCHASTIC),
        },
        "records": [], "curve": [],
    }

    age = torch.zeros(task.B, dtype=torch.long, device=args.device)
    age_min = 0                 # scalar mirror of age.min(), kept host-side (no sync)
    metrics = []
    if args.device == "cuda":
        torch.cuda.reset_peak_memory_stats()
    t0 = time.time()
    n_labelled = 0
    for step in range(args.steps):
        x, y, new_ep = task.step()
        learner._reset_lanes(new_ep)                     # learner.h + exact J
        if new_ep.any():
            for tr in trackers:
                reset_tracker_lanes(tr.algo, new_ep)
            age[new_ep] = 0
            age_min = 0
        h_prev = learner.h.detach()
        h = cell(x, h_prev)
        A, imm = cell.jac_pieces(x, h_prev, h)
        learner.algo.step_state(A, imm)                  # exact J_t
        for tr in trackers:
            with tr.rng:
                tr.algo.step_state(A, imm)               # identical (A_t, imm_t)
        age += 1
        age_min += 1
        learner.h = h.detach()

        if y is not None:
            h_leaf = learner.h.requires_grad_(True)
            outp = learner.readout(h_leaf)
            loss, metric = learner.loss_fn(outp, y)
            learner.opt.zero_grad(set_to_none=True)
            loss.backward()
            delta = h_leaf.grad.detach()
            g_true = learner.algo.grad_rows(delta)       # exact online gradient
            n_labelled += 1

            measure = (step >= args.cert_warmup and age_min >= args.cert_min_age
                       and (n_labelled - 1) % args.cert_every == 0)
            if measure:
                with torch.no_grad():
                    dn_lane = delta.norm(dim=1)                       # (B,)
                    g_flat = g_true.flatten()
                    g_norm = float(g_true.norm())
                    # scale of the Lemma-1 test: ||J_t||_F averaged over lanes
                    j_scale = float(learner.algo.J.flatten(1).norm(dim=1).mean())
                    for tr in trackers:
                        ghat = tr.algo.grad_rows(delta)
                        c = cos(ghat.flatten(), g_flat)
                        gerr = float((g_true - ghat).norm())
                        gh_norm = float(ghat.norm())
                        tr.acc["grad_cos"].append(c)
                        tr.acc["rel_err"].append(gerr / g_norm if g_norm > EPS else float("nan"))
                        tr.acc["ghat_norm"].append(gh_norm)
                        if tr.has_cert:
                            e_lane = tr.algo.e
                            bound = float((dn_lane * e_lane).mean())
                            e_mean = float(e_lane.mean())
                            trueE = None
                            if tr.has_dense:
                                E = learner.algo.J - tr.algo.residual_dense()
                                trueE = float(E.flatten(1).norm(dim=1).mean())
                            tr.acc["e_t"].append(e_mean)
                            tr.acc["bound"].append(bound)
                            if trueE is not None:
                                tr.acc["trueE"].append(trueE)
                                if trueE > 1e-12:
                                    tr.acc["tight"].append(e_mean / trueE)
                            rho = bound / gh_norm if gh_norm > EPS else float("inf")
                            tr.acc["rho_g"].append(rho)
                            tr.acc["rho_g_inf"].append(0.0 if math.isfinite(rho) else 1.0)
                            tr.acc["rho_g_lt1"].append(1.0 if rho < 1.0 else 0.0)
                            tr.cert.update(bound, gh_norm, gerr, e_mean, trueE,
                                           g_scale=max(g_norm, gh_norm),
                                           e_scale=j_scale)

            # the trainer's own update (exact RTRL) -- trackers never touch it
            cell.apply_flat_grad(g_true)
            learner.opt.step()
            cell.clip_spectral()
            learner.h = learner.h.detach()
            metrics.append(metric)

        if step % args.log_every == 0 and metrics:
            m = sum(metrics[-200:]) / len(metrics[-200:])
            rec = {"step": step, "metric": m,
                   "age_mean": age.float().mean().item(),
                   "J_norm": learner.algo.J.flatten(1).norm(dim=1).mean().item(),
                   "trk": {tr.name: tr.flush() for tr in trackers}}
            log["records"].append(rec)
            log["curve"].append({"step": step, "metric": m})
            if step % (args.log_every * 8) == 0:
                cs = " ".join(f"{k}={v.get('grad_cos', float('nan')):.3f}"
                              for k, v in rec["trk"].items())
                print(f"[{args.task}/n{args.n}/s{args.seed}] step {step} "
                      f"metric {m:.4f} | {cs}", flush=True)
        elif step % args.log_every == 0:
            for tr in trackers:
                tr.clear()

    log["wall_s"] = time.time() - t0
    log["ms_per_step"] = 1000.0 * log["wall_s"] / max(args.steps, 1)
    if args.device == "cuda":
        log["peak_MB"] = torch.cuda.max_memory_allocated() / 2 ** 20
    log["cert"] = {tr.name: tr.cert.summary() for tr in trackers if tr.cert is not None}
    log["svd_stats"] = dict(SVD_STATS)

    # trailing-window summary (per-seed aggregation over seeds is done in post-processing)
    recs = log["records"]
    k = max(1, int(round(len(recs) * args.tail_frac)))
    tailr = recs[-k:]
    log["tail_summary"] = {"n_log_points": k, "from_step": tailr[0]["step"] if tailr else None}
    for name in names:
        vals = {}
        for key in ("grad_cos", "rel_err", "e_t", "trueE", "rho_g",
                    "rho_g_inf", "rho_g_lt1", "tight"):
            v = _nanmean([r["trk"].get(name, {}).get(key) for r in tailr])
            if v is not None:
                vals[key] = v
        log["tail_summary"][name] = vals

    with open(out, "w") as f:
        json.dump(_sanitize(log), f, indent=1)
    print("saved", out, f"({log['wall_s']:.0f}s, {log['ms_per_step']:.1f} ms/step, "
          f"{log.get('peak_MB', 0):.0f}MB, {len(recs)} log points)")
    for name in names:
        v = log["tail_summary"].get(name, {})
        print(f"  {name:<12} tail grad_cos {v.get('grad_cos', float('nan')):.4f}  "
              f"rel_err {v.get('rel_err', float('nan')):.4f}"
              + (f"  rho_g {v['rho_g']:.3g}" if v.get("rho_g") is not None else "")
              + (f"  rho_g<1 {v['rho_g_lt1']:.3f} inf {v['rho_g_inf']:.3f}"
                 if "rho_g_lt1" in v else ""))


if __name__ == "__main__":
    main()
