#!/usr/bin/env bash
# R2 job queue -- Linux port of run_r2_queue.ps1 (identical semantics).
#
# One worker = one bash process pinned to one GPU.  Jobs come from a plain text
# file, one full command line per line, split across workers by kept-line index
# modulo:  worker i of k runs the lines whose kept-index satisfies  idx % k == i.
#
# Job file format
# ---------------
#   # comments and blank lines are ignored
#   run_m3.py --task henon --algo skrtrl-r16 ... --outdir results/r2/d4_tune --tag lr1e-03  # out=results/r2/d4_tune/henon_skrtrl-r16_s100_lr1e-03.json
#
# The trailing `# out=<path>` annotation is how the queue knows whether a job is
# already done (exists-skip).  It is authoritative -- no filename is ever
# re-derived from the flags -- so a job without it is always run.  A line may
# start with the .py script (the queue prepends $PY), with `python`, or with an
# explicit executable.
#
# Usage
# -----
#   run_r2_queue.sh WORKER NWORKERS DEV JOBS LOGDIR [TIMEOUT_S] [PY]
#
#   WORKER      0-based worker index          (e.g. 0)
#   NWORKERS    total number of workers       (e.g. 2)
#   DEV         GPU ordinal -> CUDA_VISIBLE_DEVICES
#   JOBS        job file, relative to this script's dir (e.g. jobs/d4_tune.txt)
#   LOGDIR      log dir, or `auto` for logs/r2/<jobs-basename>
#   TIMEOUT_S   per-job timeout in seconds    (default 10800 = 3h)
#   PY          python interpreter            (default ../env/bin/python, else python3)
#
# Detached launch (survives ssh disconnect -- this is the only supported way to
# start a long queue over ssh):
#   cd /mnt/data/Programming/research_ws/RTRL/code
#   nohup setsid ./run_r2_queue.sh 0 1 0 jobs/d4_tune.txt auto \
#         </dev/null >logs/r2/queue_w0.log 2>&1 &
#
# Each job gets a timeout (the CPU SVD fallback looks like a hang) and one retry.
# stdout+stderr of job <idx> land in <LOGDIR>/<idx>.log.

set -u

usage() { sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }
[ $# -ge 5 ] || usage

WORKER=$1
NWORKERS=$2
DEV=$3
JOBS=$4
LOGDIR=$5
TIMEOUT_S=${6:-10800}
RETRIES=1

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

if [ $# -ge 7 ] && [ -n "${7:-}" ]; then
    PY=$7
elif [ -x "$HERE/../env/bin/python" ]; then
    # canonical absolute path, so `pgrep -f .../env/bin/python` finds job processes
    PY="$(cd "$HERE/../env/bin" && pwd)/python"
else
    PY="$(command -v python3)"
fi

if [ "$WORKER" -lt 0 ] || [ "$WORKER" -ge "$NWORKERS" ]; then
    echo "Worker must be in 0..$((NWORKERS-1))" >&2; exit 2
fi
[ -f "$JOBS" ] || { echo "job file not found: $JOBS" >&2; exit 2; }

if [ "$LOGDIR" = "auto" ] || [ "$LOGDIR" = "-" ]; then
    name="$(basename "$JOBS")"; name="${name%.txt}"
    LOGDIR="logs/r2/$name"
fi
mkdir -p "$LOGDIR"

# ---- read and index the job list (index over KEPT lines only, so it is stable) ----
kept=()
while IFS= read -r line || [ -n "$line" ]; do
    t="${line#"${line%%[![:space:]]*}"}"        # ltrim
    t="${t%"${t##*[![:space:]]}"}"              # rtrim
    [ -z "$t" ] && continue
    case "$t" in \#*) continue ;; esac
    kept+=("$t")
done < "$JOBS"

total=${#kept[@]}
mine=()
for ((i = 0; i < total; i++)); do
    if [ $((i % NWORKERS)) -eq "$WORKER" ]; then mine+=("$i"); fi
done

echo "[queue] worker $WORKER/$NWORKERS  dev $DEV  jobs file $JOBS"
echo "[queue] $total jobs total, ${#mine[@]} assigned to this worker"
echo "[queue] timeout ${TIMEOUT_S}s, retries $RETRIES, logs -> $LOGDIR"
echo "[queue] python $PY"

export CUDA_VISIBLE_DEVICES="$DEV"
export PYTHONUNBUFFERED=1

nOk=0; nSkip=0; nFail=0; nTimeout=0
failed=()
t0=$(date +%s)

for idx in "${mine[@]}"; do
    line="${kept[$idx]}"

    # --- split off the "# out=<path>" annotation ---
    outPath=""
    cmd="$line"
    if [[ "$line" =~ \#[[:space:]]*out[[:space:]]*=[[:space:]]*([^[:space:]]+)[[:space:]]*$ ]]; then
        outPath="${BASH_REMATCH[1]}"
        cmd="${line:0:$(( ${#line} - ${#BASH_REMATCH[0]} ))}"
        cmd="${cmd%"${cmd##*[![:space:]]}"}"
    fi

    if [ -n "$outPath" ] && [ -f "$outPath" ]; then
        echo "[$idx] SKIP (exists) $outPath"
        nSkip=$((nSkip+1))
        continue
    fi

    # --- resolve executable and build the command line ---
    # The line is run through `eval`, so shell quoting inside a job line works
    # the same way the PowerShell queue's -ArgumentList string does.  Job files
    # are generated by make_r2_*_jobs.py, i.e. trusted input.
    read -ra argv <<< "$cmd"
    first="${argv[0]}"
    case "$first" in
        *.py)                         full="\"$PY\" $cmd" ;;
        python|python3|py|python.exe) full="\"$PY\" ${cmd#"$first"}" ;;
        *)                            full="$cmd" ;;   # explicit executable, as is
    esac

    log="$LOGDIR/$idx.log"
    ok=0; timedOut=0; code=-1
    for ((attempt = 1; attempt <= 1 + RETRIES; attempt++)); do
        stamp=$(date -Is)
        {
            echo "==== [$idx] attempt $attempt dev $DEV $stamp ===="
            echo "==== cmd: $full"
        } >> "$log"
        timedOut=0
        eval "timeout -k 30 ${TIMEOUT_S}s $full" >> "$log" 2>&1
        code=$?
        if [ "$code" -eq 124 ] || [ "$code" -eq 137 ]; then timedOut=1; fi

        producedOut=1
        if [ -n "$outPath" ] && [ ! -f "$outPath" ]; then producedOut=0; fi

        if [ "$timedOut" -eq 0 ] && [ "$code" -eq 0 ] && [ "$producedOut" -eq 1 ]; then
            ok=1; break
        fi
        if [ "$timedOut" -eq 1 ]; then why="TIMEOUT"
        elif [ "$code" -ne 0 ];   then why="exit $code"
        else                           why="no output file"
        fi
        echo "[$idx] attempt $attempt failed ($why)"
        echo "==== [$idx] attempt $attempt failed ($why)" >> "$log"
    done

    if [ "$ok" -eq 1 ]; then
        echo "[$idx] OK   $cmd"
        nOk=$((nOk+1))
    else
        [ "$timedOut" -eq 1 ] && nTimeout=$((nTimeout+1))
        nFail=$((nFail+1))
        failed+=("$idx")
        echo "[$idx] FAIL $cmd  (see $log)"
    fi
done

dt=$(( ($(date +%s) - t0) / 60 ))
echo "--------------------------------------------------------------"
echo "[queue] worker $WORKER done in $dt min"
echo "[queue] assigned ${#mine[@]}  ok $nOk  skipped $nSkip  failed $nFail  (of which timeouts $nTimeout)"
if [ ${#failed[@]} -gt 0 ]; then
    echo "[queue] failed job indices: $(IFS=,; echo "${failed[*]}")"
    exit 1
fi
